[server]
headless = true
address = "0.0.0.0"
enableCORS = false
enableXsrfProtection = false
enableWebsocketCompression = true
fileWatcherType = "none"
maxUploadSize = 50

[browser]
gatherUsageStats = false
